site_name: EMBL-EBI Cloud Portal Documentation's
pages:

- Home: index.md
- Dev documentation: dev_documentation.md
- Securing Credentials: securing_credentials.md
- Mkdocs: mkdocs.md
theme: readthedocs
